{
 "title": "CSGO Stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Weapon kills",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "CSGOstats_total_kills_aug", "legendFormat": "Kills AUG" },
    { "expr": "CSGOstats_total_kills_awp", "legendFormat": "Kills AWP" },
    { "expr": "CSGOstats_total_kills_deagle", "legendFormat": "Kills Deagle" },
    { "expr": "CSGOstats_total_kills_famas", "legendFormat": "Kills Famas" },
    { "expr": "CSGOstats_total_kills_m4a1", "legendFormat": "Kills M4A1" },
    { "expr": "CSGOstats_total_kills_sg556", "legendFormat": "Kills SG556" },
    { "expr": "CSGOstats_total_kills_ak47", "legendFormat": "Kills AK47" }
   ]
  },
  {
   "title": "K/D",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "CSGOstats_total_kills/CSGOstats_total_deaths"
    }
   ]
  },
  {
   "title": "Headshot %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "CSGOstats_total_kills_headshot/CSGOstats_total_kills"
    }
   ]
  },
  {
   "title": "Kills last match",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    { "expr": "CSGOstats_last_match_kills" }
   ]
  },
  {
   "title": "Total Kills",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "CSGOstats_total_kills" }
   ]
  },
  {
   "title": "Kills AK-47",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "CSGOstats_total_kills_ak47" }
   ]
  }
 ]
}